# medispatcher config file. It should be placed to /etc/medispacher.toml
# TOML v0.2 FORMAT
DAEMON_USER="www-data"

LOG_DIR="/var/log/medispatcher"

# 提供RPC服务的地址. 如：缓存清除、参数动态调节等。
ListenAddr="0.0.0.0:5601"

# 队列服务器地址, 如beanstalkd的为 127.0.0.1:11300
QueueServerAddr="127.0.0.1:11300"

NameOfMainQueue="event_center_messages"

PrefixOfChannelQueue="sub-queue/"

# 开启消息推送日志
EnableMsgSentLog=true


# 主队列上消息分发并发数
ListenersOfMainQueue=10

# 每个订阅允许的最大并发推送数
MaxSendersPerChannel=10

# 每个订阅(重试时)允许的最大并发推送数
MaxSendersPerRetryChannel=5

# 每个订阅默认的并发推送数
SendersPerChannel=5

# 每个订阅(重试时)默认的并发推送数
SendersPerRetryChannel=2

# 每个订阅单线程上最小推送间隔时间(ms)。
IntervalOfSendingForSendRoutine=10

# 每个消息允许的最大处理时间(ms)。
MaxMessageProcessTime=30000

# (默认的)每个消息允许的最大处理时间(ms)
DefaultMaxMessageProcessTime=5000

# 重试延时参数. 值越大，下一次推送时间滞后越大.
# interval = pow(retryTimes+1, 2)*CoeOfIntervalForRetrySendingMsg
CoeOfIntervalForRetrySendingMsg=1

MsgQueueFaultToleranceListNamePrefix="event_center_message_in_failure_log:"

[Database]
Host="192.168.25.9"
Port=3306
User="dev"
Password="jumeidevforall"
DbName="jm_event"

[Redis]
Addr="127.0.0.1:6379"
DbIndex=4