#TOML v0.2 FORMAT
DAEMON_USER="www-data"

LOG_DIR="/var/log/medispatcher"
ListenAddr="0.0.0.0:5601"

QueueServerAddr="127.0.0.1:11300"

NameOfMainQueue="event_center_messages"

PrefixOfChannelQueue="sub-queue/"

EnableMsgSentLog=true

ListenersOfMainQueue=10

SendersPerChannel=5
SendersPerRetryChannel=2

# (正常队列上)每个订阅单线程上最小推送间隔时间。
IntervalOfSendingForSendRoutine=100

# (重试队列上)每个订阅单线程上最小推送间隔时间。
IntervalOfSendingForSendRoutineOfRetry=100

# 重试延时参数. 值越大，下一次推送时间滞后越大.
# interval = pow(retryTimes+1, 2)*CoeOfIntervalForRetrySendingMsg
CoeOfIntervalForRetrySendingMsg=1

MsgQueueFaultToleranceListNamePrefix="event_center_message_in_failure_log:"
[Database]
Host="192.168.25.9"
Port=3306
User="dev"
Password="jumeidevforall"
DbName="jm_event"

[Redis]
Addr="127.0.0.1:6379"
DbIndex=4